//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posyandu
{
    using System;
    using System.Collections.Generic;
    
    public partial class kebersihanGigiAnak
    {
        public string NIK { get; set; }
        public string namaAnak { get; set; }
        public string jenisKelamin { get; set; }
        public System.DateTime tanggalPeriksa { get; set; }
        public Nullable<bool> kebersihanGigi { get; set; }
        public Nullable<bool> karies { get; set; }
    
        public virtual balita balita { get; set; }
    }
}
