//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posyandu
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DatabasePsoyanduEntities : DbContext
    {
        public DatabasePsoyanduEntities()
            : base("name=DatabasePsoyanduEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<balita> balitas { get; set; }
        public virtual DbSet<kebersihanGigiAnak> kebersihanGigiAnaks { get; set; }
        public virtual DbSet<orangtua> orangtuas { get; set; }
        public virtual DbSet<pemberianVitaminA> pemberianVitaminAs { get; set; }
        public virtual DbSet<penerimaObatCacing> penerimaObatCacings { get; set; }
        public virtual DbSet<petuga> petugas { get; set; }
        public virtual DbSet<polaMakan> polaMakans { get; set; }
        public virtual DbSet<RecordTimbangPersonal> RecordTimbangPersonals { get; set; }
        public virtual DbSet<userAccount> userAccounts { get; set; }
    }
}
