//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posyandu
{
    using System;
    using System.Collections.Generic;
    
    public partial class petuga
    {
        public string NIK { get; set; }
        public string namaPetugas { get; set; }
        public string noTelp { get; set; }
        public string peran { get; set; }
        public Nullable<System.DateTime> tanggalLahirKader { get; set; }
    
        public virtual userAccount userAccount { get; set; }
    }
}
