//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posyandu
{
    using System;
    using System.Collections.Generic;
    
    public partial class polaMakan
    {
        public string NIK { get; set; }
        public string namaAnak { get; set; }
        public string daftarMakan { get; set; }
        public string intervensiGizi { get; set; }
        public string teksturMakanan { get; set; }
        public string frekuensiMakan { get; set; }
    
        public virtual balita balita { get; set; }
    }
}
