//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Posyandu
{
    using System;
    using System.Collections.Generic;
    
    public partial class RecordTimbangPersonal
    {
        public string NIK { get; set; }
        public string namaAnak { get; set; }
        public System.DateTime Tanggal_Timbang { get; set; }
        public int Berat_Badan { get; set; }
        public Nullable<double> Tinggi_Badan { get; set; }
        public string Status_Gizi { get; set; }
    
        public virtual balita balita { get; set; }
    }
}
